import { useEffect, useState } from 'react'

const Icon = ({ name, size = 22 }) => {
  const icons = { star: '★', gift: '✦', play: '▶', arrow: '→', check: '✓', close: '×', fire: '✷', spark: '✺', bolt: 'ϟ' }
  return <span aria-hidden="true" style={{ fontSize: size }}>{icons[name]}</span>
}

function Header({ onReview }) {
  return <header className="header"><a className="logo" href="#home" aria-label="Macboom home"><span>mac</span>boom<i>.</i></a><nav><a href="#cara-kerja">Cara kerja</a><a href="#games">Games</a><a href="#hadiah">Rewards</a><button onClick={onReview}>Review Macboom</button></nav></header>
}

function ProductVisual() {
  return <div className="product-stage" aria-label="Ilustrasi kemasan Macboom"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="floating-chip chip-one">✦</span><span className="floating-chip chip-two">✷</span><div className="packet"><div className="packet-top"/><div className="packet-brand">mac<span>boom</span><sup>®</sup></div><div className="packet-label">MAKARONI<br/><strong>SAUS PEDAS</strong></div><div className="packet-bowl"><span>〰</span><span>〰</span><span>〰</span></div><div className="packet-bottom">RASA JUARA <b>•</b> 100% NAGIH</div></div><div className="scan-badge"><div className="qr-mini"><i/><i/><i/><i/><i/></div><span>SCAN ME!</span></div></div>
}

function StepCard({ number, icon, title, text, color }) { return <article className={`step-card ${color}`}><div className="step-number">0{number}</div><div className="step-icon"><Icon name={icon} size={26}/></div><h3>{title}</h3><p>{text}</p></article> }
const Scale = ({ label, value, onChange }) => <div className="scale-field"><span>{label}</span><div>{[1,2,3,4,5].map(n => <button type="button" key={n} className={n <= value ? 'active' : ''} onClick={() => onChange(n)} aria-label={`${label} ${n} dari 5`}>{n}</button>)}</div><small>{value ? ['','Kurang','Cukup','Oke','Enak','Juara!'][value] : 'Pilih nilai'}</small></div>

function ReviewModal({ onClose, onReward }) {
  const [rating, setRating] = useState(0); const [sent, setSent] = useState(false)
  const [scores, setScores] = useState({ crunch: 0, taste: 0, pack: 0, price: 0 })
  const setScore = (name, value) => setScores({ ...scores, [name]: value })
  const submit = e => { e.preventDefault(); if (rating && Object.values(scores).every(Boolean)) { setSent(true); onReward(20) } }
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Review Macboom"><div className="review-modal review-long"><button className="close" onClick={onClose}><Icon name="close"/></button>{sent ? <div className="thanks"><div className="thanks-icon">✓</div><p className="eyebrow">+20 BOOM POINTS</p><h2>Terima kasih!</h2><p>Review kamu sudah masuk. Poin Boom sudah ditambahkan ke akunmu.</p><button className="dark-button" onClick={onClose}>Mantap!</button></div> : <form onSubmit={submit}><span className="eyebrow">REVIEW MACBOOM · +20 POIN</span><h2>Gimana Macboom-mu?</h2><p className="modal-copy">Ulasan jujurmu bantu kami bikin makaroni yang makin boom.</p><label className="field-label">Rating keseluruhan</label><div className="stars" aria-label="Pilih rating">{[1,2,3,4,5].map(n => <button type="button" key={n} className={n <= rating ? 'selected' : ''} onClick={() => setRating(n)} aria-label={`${n} bintang`}>★</button>)}</div><label className="field-label">Varian rasa</label><select required defaultValue=""><option value="" disabled>Pilih varian yang kamu coba</option><option>Original Pedas</option><option>Extra Pedas</option><option>Balado</option><option>Keju</option></select><div className="review-scales"><Scale label="Kerenyahan" value={scores.crunch} onChange={n => setScore('crunch', n)}/><Scale label="Rasa" value={scores.taste} onChange={n => setScore('taste', n)}/><Scale label="Kemasan" value={scores.pack} onChange={n => setScore('pack', n)}/><Scale label="Harga" value={scores.price} onChange={n => setScore('price', n)}/></div><label className="field-label">Komentar atau saran</label><textarea placeholder="Ceritakan pengalamanmu..." required/><label className="buy-again"><input type="checkbox"/> <span>Mau beli Macboom lagi!</span></label><button className="dark-button" type="submit">Kirim review +20 poin <Icon name="arrow"/></button></form>}</div></div>
}

function CatchGame({ onEarn }) { const [caught, setCaught] = useState(0); const [done, setDone] = useState(false); const catchIt = () => { const next = caught + 1; setCaught(next); if (next === 5) { setDone(true); onEarn(10) } }; return <div className="game-play catch-play"><div className="game-status"><span>TERTANGKAP</span><b>{caught}/5</b></div>{done ? <div className="game-win">✨ Mantap! +10 Boom Points</div> : <><p>Klik makaroni yang jatuh ke keranjang!</p><button className="falling-mac" onClick={catchIt} aria-label="Tangkap makaroni">〰</button><div className="basket">⌒⌒⌒</div></>}</div> }
function TapGame({ onEarn }) { const [time, setTime] = useState(15); const [taps, setTaps] = useState(0); const [running, setRunning] = useState(false); const [finished, setFinished] = useState(false); useEffect(() => { if (!running || time === 0) return; const timer = setTimeout(() => setTime(t => t - 1), 1000); return () => clearTimeout(timer) }, [running, time]); useEffect(() => { if (running && time === 0) { setRunning(false); setFinished(true); onEarn(10) } }, [time, running, onEarn]); const start = () => { setTime(15); setTaps(0); setFinished(false); setRunning(true) }; return <div className="game-play tap-play"><div className="timer">{time}<small>DETIK</small></div>{!running && !finished && <button className="cream-button" onClick={start}>Mulai 15 detik <Icon name="play"/></button>}{running && <button className="tap-mac" onClick={() => setTaps(t => t + 1)} aria-label="Tap makaroni">✦<span>TAP!</span></button>}{finished && <div className="game-win">{taps} tap! +10 Boom Points<br/><button onClick={start}>Main lagi</button></div>}<p>Skor: <b>{taps}</b></p></div> }
function LuckyGame({ onEarn }) { const prizes = ['+10 Boom Points','Voucher Diskon 10%','Coba lagi, ya!','+20 Boom Points']; const [prize, setPrize] = useState(''); const dip = () => { const result = prizes[Math.floor(Math.random() * prizes.length)]; setPrize(result); if (result.includes('Points')) onEarn(Number(result.match(/\d+/)[0])) }; return <div className="game-play lucky-play"><div className="drop-machine"><span>〰</span><span>✦</span><span>〰</span></div><p>{prize || 'Jatuhkan makaroni dan lihat hadiahmu!'}</p><button className="cream-button" onClick={dip}>{prize ? 'Coba lagi' : 'Jatuhkan makaroni'} <Icon name="arrow"/></button></div> }

function Games({ onEarn }) { const [active, setActive] = useState('catch'); const games = { catch: { title: 'Catch the Macboom', text: 'Tangkap makaroni yang jatuh ke keranjang.', render: <CatchGame onEarn={onEarn}/> }, tap: { title: 'Tap the Boom', text: 'Tekan makaroni sebanyak mungkin dalam 15 detik.', render: <TapGame onEarn={onEarn}/> }, lucky: { title: 'Boom Lucky Dip', text: 'Jatuhkan makaroni dan lihat hadiahmu!', render: <LuckyGame onEarn={onEarn}/> } }; const game = games[active]; return <section className="games-section" id="games"><div className="section-heading"><div><p className="kicker orange"><span/> MAIN & MENANG</p><h2>Waktunya bikin<br/><em>boom!</em></h2></div><p>Mainkan game pilihanmu. Selesaikan tantangan untuk dapat poin atau kesempatan hadiah.</p></div><div className="game-tabs">{Object.entries(games).map(([id, item], index) => <button key={id} onClick={() => setActive(id)} className={active === id ? 'active' : ''}><span>0{index + 1}</span>{item.title}</button>)}</div><div className="game-board"><div className="game-board-copy"><p className="kicker light"><span/> MINI GAME MACBOOM</p><h2>{game.title}</h2><p>{game.text}</p><small>Hadiah game dapat berubah sesuai periode promosi.</small></div>{game.render}</div></section> }

function Rewards({ points }) { const activities = [['Scan QR kemasan', '10 poin'],['Mengisi review', '20 poin'],['Memainkan mini game', '10 poin'],['Skor tertentu', 'Bonus poin'],['Bagikan Macboom', 'Bonus poin'],['Beli lagi', 'Bonus poin']]; return <section className="rewards" id="hadiah"><div className="reward-copy"><p className="kicker orange"><span/> BOOM POINTS</p><h2>Ngemilnya dapat,<br/><em>hadiahnya</em> juga dapat.</h2><p>Setiap aktivitas bikin poinmu bertambah. Tukarkan dengan reward yang kamu suka!</p><div className="point-balance"><span>POIN KAMU</span><b>{points}</b><small>Boom Points</small></div></div><div><div className="activity-list"><h3>Cara kumpulkan poin</h3>{activities.map(([activity, value]) => <div key={activity}><span>{activity}</span><b>+{value}</b></div>)}</div><div className="reward-grid"><div className="reward-item sticker"><span className="points">2.500 PTS</span><div>☄</div><h3>Sticker pack</h3></div><div className="reward-item hoodie"><span className="points">15.000 PTS</span><div>♜</div><h3>Macboom hoodie</h3></div><div className="reward-item voucher"><span className="points">5.000 PTS</span><div>Rp</div><h3>Voucher jajan</h3></div></div><p className="reward-note">Voucher, diskon, DANA Kaget, dan ShopeePay Kaget merupakan reward terbatas berdasarkan ketersediaan anggaran serta periode promosi. Tidak semua pembeli pasti memperoleh reward tunai.</p></div></section> }

function App() { const [reviewOpen, setReviewOpen] = useState(false); const [points, setPoints] = useState(10); const earn = amount => setPoints(value => value + amount); return <main id="home"><Header onReview={() => setReviewOpen(true)}/><section className="hero"><div className="hero-copy"><p className="kicker"><span/> MAKAN ENAK, DAPAT LEBIH</p><h1>Scan.<br/><em>Play.</em> Repeat.</h1><p className="hero-text">Setiap bungkus Macboom punya kejutan. Scan QR-nya, mainkan gamenya, dan kumpulkan reward-mu!</p><div className="hero-actions"><a href="#games" className="primary-button">Mulai petualangan <Icon name="arrow"/></a><button className="text-button" onClick={() => setReviewOpen(true)}>Review Macboom <Icon name="star" size={17}/></button></div><div className="social-proof"><div className="avatars"><b>R</b><b>A</b><b>N</b><b>+</b></div><span><strong>12.8K+</strong> Boomers sudah ikut!</span></div></div><ProductVisual/><div className="scroll-note"><span/> SCROLL UNTUK MENJELAJAH</div></section><section className="how" id="cara-kerja"><div className="section-heading"><div><p className="kicker orange"><span/> GAMPANG BANGET</p><h2>Cuma 3 langkah<br/>buat dapet <em>boom!</em></h2></div><p>Bungkus Macboom bukan cuma buat ngemil. Ada pengalaman seru yang nungguin kamu di dalamnya.</p></div><div className="steps"><StepCard number="1" icon="spark" title="Scan QR-nya" text="Arahkan kamera ke QR code di kemasan Macboom." color="yellow"/><StepCard number="2" icon="play" title="Main & review" text="Coba mini game seru atau kasih ulasan jujur kamu." color="orange"/><StepCard number="3" icon="gift" title="Klaim reward" text="Kumpulkan poin dan tukar dengan hadiah pilihanmu." color="purple"/></div></section><Games onEarn={earn}/><Rewards points={points}/><footer><a className="logo" href="#home"><span>mac</span>boom<i>.</i></a><p>Teman ngemil paling <b>boom!</b></p><div><a href="#home">Instagram</a><a href="#home">TikTok</a><a href="#home">Kontak</a></div><small>© 2025 Macboom. Dibuat untuk para pecinta rasa.</small></footer>{reviewOpen && <ReviewModal onClose={() => setReviewOpen(false)} onReward={earn}/>}</main> }
export default App
